### ISSUE TITLE
Use dotnetcore instead of Mono

### ISSUE THREAD

**Issue by thekid** [xp-runners/reference#73]
## Resources

* https://blogs.msdn.microsoft.com/luisdem/2016/10/11/net-core-how-to-publish-a-self-contained-application-exe/
* https://docs.microsoft.com/en-us/dotnet/core/deploying/index
* https://stackoverflow.com/questions/38085430/the-library-hostpolicy-dll-was-not-found
* https://docs.microsoft.com/en-us/dotnet/core/rid-catalog
* https://docs.microsoft.com/de-de/dotnet/core/tools/project-json-to-csproj
* https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties

**Comment by thekid** [comment]
### src/xp.runner/xp.runner.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Company>XP-Framework Team</Company>
    <Authors>XP Runners</Authors>
    <AssemblyTitle>XP Runner</AssemblyTitle>
    <Copyright>Copyright XP-Framework Team 2001-2017</Copyright>
    <Version>8.1.0.1353</Version>
    <StartupObject>Xp.Runners.Xp</StartupObject>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

*Also delete AssemblyInfo.cs to prevent "duplicate attribute" errors!*

```bash
$ dotnet run -- list
@C:\...\src\xp.runner\bin\Debug\netcoreapp2.0\xp.runner.dll
XP Subcommands
════════════════════════════════════════════════════════════════════════

> Builtin @ 8.1.0.1353

  $ xp ar
  $ xp dump
  $ xp eval
  $ xp help
  $ xp list
  $ xp run
  $ xp version
  $ xp write

> Installed @ C:\Users\Timm\AppData\Roaming\Composer\vendor

  $ xp mirror (» from xp-forge/mirrors)
  $ xp sql (» from xp-forge/sql)
  $ xp cmd (» from xp-framework/command)
  $ xp test (» from xp-framework/unittest)
```

**Comment by thekid** [comment]
## Performance

### Self-contained deployment (Windows)
Created with dotnet publish -c Release -r win10-x64

```bash
$ du -ksh ./bin/Release/netcoreapp2.0/win10-x64/publish
63M     ./bin/Release/netcoreapp2.0/win10-x64/publish

$ time ./bin/Release/netcoreapp2.0/win10-x64/publish/xp.runner.exe version runners
Runners/8.1.0.1353

real    0m0.229s
user    0m0.015s
sys     0m0.000s
```

### Framework-dependent deployment
Created with dotnet publish -f netcoreapp2.0 -c Release

```bash
$ du -ksh ./bin/Release/netcoreapp2.0/publish/
102K    ./bin/Release/netcoreapp2.0/publish/

$ time dotnet ./bin/Release/netcoreapp2.0/publish/xp.runner.dll version runners
Runners/8.1.0.1353

real    0m0.229s
user    0m0.062s
sys     0m0.000s
```

### Mono-compiled runners running on Windows
Created by mcs -r:System.Runtime.Serialization src/... -target:exe -main:Xp.Runners.Xp

```bash
$ du -ksh ~/bin/xp.exe
68K     /home/Timm/bin/xp.exe

$ time xp version runners
Runners/8.1.0.414

real    0m0.206s
user    0m0.000s
sys     0m0.000s
```

### Self-contained deployment (WSL)
Created with dotnet publish -c Release -r ubuntu.14.04-x64

```bash
$ du -ksh ./bin/Release/netcoreapp2.0/ubuntu.14.04-x64/publish/
63M     ./bin/Release/netcoreapp2.0/ubuntu.14.04-x64/publish/

$ time ./bin/Release/netcoreapp2.0/ubuntu.14.04-x64/publish/xp.runner version runners
Runners/8.1.0.1353

real    0m2.425s
user    0m0.156s
sys     0m0.953s
```

### Mono-compiled runners running on WSL
Created by mcs -r:System.Runtime.Serialization src/... -target:exe -main:Xp.Runners.Xp

```bash
$ du -ksh /usr/bin/xp*
0       /usr/bin/xp
68K     /usr/bin/xp.exe

$ time xp version runners
Runners/8.1.0.414

real    0m1.449s
user    0m0.078s
sys     0m0.219s
```

**Comment by thekid** [comment]
Also, a bug occurs when running on WSL:

```bash
thekid@slate /mnt/c/tools/cygwin/home/Timm/devel/runners/reference/src/xp.runner [master]
$ time ./bin/Release/netcoreapp2.0/ubuntu.14.04-x64/publish/xp.runner list
@/mnt/c/tools/cygwin/home/Timm/devel/runners/reference/src/xp.runner/bin/Release/netcoreapp2.0/ubuntu.14.04-x64/publish/xp.runner.dll
XP Subcommands
════════════════════════════════════════════════════════════════════════

> Builtin @ 8.1.0.1353


Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Xp.Runners.Commands.List.BuiltinsIn(Assembly assembly) in C:\tools\cygwin\home\Timm\devel\runners\reference\src\xp.runner\commands\List.cs:line 19
   at Xp.Runners.Commands.List.Execute(CommandLine cmd, ConfigSource configuration) in C:\tools\cygwin\home\Timm\devel\runners\reference\src\xp.runner\commands\List.cs:line 82
   at Xp.Runners.Xp.Main(String[] args) in C:\tools\cygwin\home\Timm\devel\runners\reference\src\xp.runner\Xp.cs:line 14
Aborted (core dumped)

real    0m1.277s
user    0m0.109s
sys     0m0.188s
```
